spring:
  datasource:
    mysql:
      jdbcUrl: jdbc:mysql://118.114.244.93:13306/cdss_dev?useUnicode=true&characterEncoding=utf-8&useSSL=true
      username: root
      password: root
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver
      initialSize: 3
      minIdle: 3
      maxIdle: 20
      maxActive: 30
      maxWait: 30000
      validationQuery: SELECT 'x'
      testWhileIdle: true
      testOnBorrow: false
      numTestsPerEvictionRun: 3
      timeBetweenEvictionRunsMillis: 30000
      minEvictableIdleTimeMillis: 1800000
  data:
    solr:
      host: http://192.168.198.129:8983/solr/demo_core

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true


mybatis:
  mapper-locations: mapping/*.xml

# 分布式事物
## tx-manager 配置
tx-lcn:
  client:
    manager-address: 127.0.0.1:8070
  ribbon:
    loadbalancer:
      dtx:
        enabled: true
