spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://118.114.244.93:13306/bi_dev?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
    initialSize: 10
    maxActive: 30
    maxIdle: 20
    maxWait: 60000
    minEvictableIdleTimeMillis: 300000
    minIdle: 10
    numTestsPerEvictionRun: 3
    testOnBorrow: false
    testWhileIdle: true
    removeAbandoned: true
    removeAbandonedTimeout: 180
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: 'SELECT ''x'' '
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true


mybatis:
  mapper-locations: mapping/*.xml

# 分布式事物
## tx-manager 配置
tx-lcn:
  client:
    manager-address: 127.0.0.1:8070
  ribbon:
    loadbalancer:
      dtx:
        enabled: true