server:
  port: 8888

spring:
  application:
    name: zuul
  profiles:
    active: dev

zuul:
  host:
    connect-timeout-millis: 8000
    socket-timeout-millis: 10000
  ignoredServices: '*'
  ignoreSecurityHeaders: false
  sensitiveHeaders:
  routes:
    aaa:
      path: /testa-api/**
      serviceId: testA
    bbb:
      path: /testb-api/**
      serviceId: testB
    system:
      path: /system-api/**
      serviceId: system
      #rpc:
      #path: /rpc-api/**
      #serviceId: rpc

security:
  basic:
  enabled: false


feign:
  hystrix:
    enabled: true #开启Hystrix以支持服务熔断[高版本默认false关闭]，如果置为false，则请求超时交给ribbon控制.
  httpclient:
    connection-timeout: 5000

##设置服务熔断超时时间[默认1s]
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 20000 #设置为20s。计算公式(Ribbon)= (ReadTimeout + ConnectTimeout) * (maxAutoRetries + 1) * (maxAutoRetriesNextServer + 1)

ribbon:
  eureka:
    enable: true
  ReadTimeout: 3000 #ribbon请求处理的超时时间3s
  ConnectTimeout: 2000 #ribbon请求连接的超时时间2s
  MaxAutoRetries: 1 #单个节点（服务器）最大重试次数，不包括首次调用
  MaxAutoRetriesNextServer: 1 #最多重试多少台个节点（服务器）,不包括首次调用
  OkToRetryOnAllOperations: false  #设置为false，只会对get请求进行重试,设置为true，便会对所有的请求进行重试